#!/bin/env python

Import('*')

#######################################
# ENVIRONMENT   
#######################################
env = env.Copy();

#######################################
# CHECKS
#######################################
if not env.GetOption('clean'):
	config = env.Configure(log_file = '/dev/null')
	config_ok = True

	if not config.CheckHeader('curl/curl.h'):
		print "You need to install the cURL development libraries"
		config_ok = False

	if not config_ok:
		Exit(1)

	env = config.Finish()

#######################################
# TARGETS
#######################################
srcs = Split("""wwfetch_init.c
		wwfetch_data.c
		wwfetch_http.c
		wwfetch_fetch.c
		wwfetch_image.c
		wwfetch_error.c""")

libwwfetch = env.StaticLibrary('libwwfetch', [srcs])

#if env.GetOption('clean') or int(env['extras']):
#	SConscript('examples/SConscript', exports = ['env'])

Return('libwwfetch')
