#!/bin/env python

Import('*')

#######################################
# ENVIRONMENT   
#######################################
env = env.Copy();

#######################################
# TARGETS
#######################################
srcs = Split("""wwfetch_init.c
		wwfetch_data.c
		wwfetch_http.c
		wwfetch_fetch.c
		wwfetch_image.c
		wwfetch_error.c""")

libwwfetch = env.StaticLibrary('libwwfetch', [srcs])

#if env.GetOption('clean') or int(env['extras']):
#	SConscript('examples/SConscript', exports = ['env'])

Return('libwwfetch')
