#!/bin/env python

Import('*')

#######################################
# ENVIRONMENT
#######################################
env = env.Copy();

#######################################
# TARGETS
#######################################
srcs = Split("""tiledb_file_io.c
		tiledb_file_locking.c
		tiledb_internal.c
		tiledb_filesystem_import.c
		tiledb_endian.c
		tiledb_cache.c
		tiledb.c""")

libtiledb = env.StaticLibrary('libtiledb', [srcs])

Return('libtiledb')
